language: matlab
script: matlab -batch "addpath('code'); results = runtests('IncludeSubfolders', true); assertSuccess(results);"
notifications:
  email:
    recipients:
      - $CI_INTERNAL_EMAIL
    on_success: change
    on_failure: always